First iteration
sirin7/go_final_project pull request #1
Opened 2024-09-03 15:02 UTC by sirin7

2024-09-04 12:08 UTC, dirtymew requested changes
Привет Светлана

хорошая работа - супер что добавила документацию и логирование

дал рекомендации что поправить и улучшить

задания со звездочкой если будешь делать то нужно сразу - после того как приму задание на ревью уже не получиться ничего отправить

2024-09-04 12:08 UTC, dirtymew commented on README.md
> +Директория `web` содержит файлы фронтенда.
отлично что добавила документацию

стоит описать подробнее как настроить запустить тесты и приложения

мб добавить примеры команд

2024-09-04 12:08 UTC, dirtymew commented on handlers/delete_task.go
> +package handlers
бинарник go_final_project лучше не комитеть в репозиторий

2024-09-04 12:08 UTC, dirtymew commented on models/models.go
> +func GetAllTasks(db *sql.DB) ([]Task, error) {
это к моделям не относится - стоит вынести в отдельный пакет или в пакет database

2024-09-04 12:08 UTC, dirtymew commented on models/models.go
> +	rows, err := db.Query("SELECT id, date, title, comment, repeat FROM scheduler ORDER BY date ASC LIMIT 50")
лимит вынести в константу

2024-09-04 12:08 UTC, dirtymew commented on models/models.go
> +	log.Println("Получены задачи из таблицы scheduler")
лучше не логировать каждый запрос - только ошибки 

ну или использовать продвинутый логгер с несколькими уровнями логирования и режим работы в debug - но это за рамками курса

2024-09-04 12:08 UTC, dirtymew commented on models/models.go
> +func GetAllTasks(db *sql.DB) ([]Task, error) {
посмотри как storage был в задании про посылки организован

2024-09-04 12:08 UTC, dirtymew commented on helpers/nextDate.go
> +func DecodeJSON(body io.ReadCloser, v interface{}) error {
кажется дубль уже было в models - мб вынести в пакет другой

2024-09-04 12:08 UTC, dirtymew commented on handlers/put_task.go
> +func (h *Handler) PutTask(w http.ResponseWriter, r *http.Request) {
Общие рекомендации по рефакторингу:

- вся логика организована в хендлерах - проект не мальнький и они уже перегружены проверками и запросами - стоит провести рефакторинг
- по структуре проекта https://github.com/golang-standards/project-layout
- по архитектуре - https://medium.com/@shershnev/layered-architecture-implementation-in-golang-6318a72c1e10 и в задании про посылки можно подсмотреть как организованы service и storage
- проверки лучше вынести в методы/функции и другие пакеты

это не обязательно так как в курсе подробно не рассматривалось

2024-09-04 12:08 UTC, dirtymew commented on handlers/put_task.go
> +	taskFromDB, err := models.GetTaskById(h.DB, id)
кажется что лишний вызов и запрос sql

кажется что models.PutTask(h.DB, task)  должно хватить  

если нужно вернуть "task not found" - то в update можно обработать RowsAffected

2024-09-04 12:08 UTC, dirtymew commented on handlers/delete_task.go
> +	taskFromDB, err := models.GetTaskById(h.DB, id)
см комент в put - тут лишний запрос sql все можно одним сделать delete

2024-09-04 12:08 UTC, dirtymew commented on handlers/delete_task.go
> +	w.Write([]byte(fmt.Sprint(`{}`)))
тут и везде _ , _ = w.Write()
тут стоит либо явно проигнорировать ошибку или ее логировать

2024-09-04 12:08 UTC, dirtymew commented on handlers/get_date_task.go
> +		w.Write([]byte(`{"error": "invalid now date format"}`))
ошибки принято на каком-то одном языке писать - у тебя то на русском то на английском

2024-09-04 12:08 UTC, dirtymew commented on main.go
> +	log.Println("Сервер запущен на порту 7540")
это никогда не выполнится - нужно перед ListenAndServe

2024-09-04 12:08 UTC, dirtymew commented on main.go
> +		fmt.Printf("ошибка запуска сервера: %s\n", err.Error())
используй по всему проекту для логирования что-то одно раз есть log то fmt.Printf не пользуйся

2024-09-04 12:08 UTC, dirtymew commented on main.go
> +	appPath, err := os.Executable()
os.Executable() у всех по разному работает - лучше сделать так чтобы по умолчанию в коревой папке проекта db создавалась

2024-09-04 12:08 UTC, dirtymew commented on main.go
> +	db, err := sql.Open("sqlite", "scheduler.db")
а если ее нет? сначала надо проверить что есть 

если нет то создавать

2024-09-04 12:08 UTC, dirtymew commented on main.go
> +	r.Get("/api/task", handler.GetTaskId)
это бы вынести в пакет - main немного уже перегружен

2024-09-11 13:24 UTC, sirin7 commented
> Привет Светлана
> 
> хорошая работа - супер, добавила документацию и регистрацию
> 
> Дальние рекомендации, что исправить и улучшить
> 
> задание со звездочкой, если будешь делать это нужно сразу - после того как приму задание на ревью уже не получиться ничего отправить

Привет,
Постаралась по максимум исправить замечания 
Хотела еще добавить докер, но не сложилось (
![image](https://github.com/user-attachments/assets/8928ab44-abf5-4578-803c-be8fd25a3b50)
Так и не поняла, почему при запуске контейнера возникла ошибка, решила отправить уже без него

2024-09-12 08:57 UTC, dirtymew commented
> > Привет Светлана
> > хорошая работа - супер, добавила документацию и регистрацию
> > Дальние рекомендации, что исправить и улучшить
> > задание со звездочкой, если будешь делать это нужно сразу - после того как приму задание на ревью уже не получиться ничего отправить
> 
> Привет Спасибо!
> 
> Постаралась по максимум исправить замечания Хотела еще добавить докер, но не сложилось ( ![image](https://private-user-images.githubusercontent.com/165197272/366473946-8928ab44-abf5-4578-803c-be8fd25a3b50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMzE2NzAsIm5iZiI6MTcyNjEzMTM3MCwicGF0aCI6Ii8xNjUxOTcyNzIvMzY2NDczOTQ2LTg5MjhhYjQ0LWFiZjUtNDU3OC04MDNjLWJlOGZkMjVhM2I1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQwODU2MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTU5NjY4ZDM0MzNkNTM0MTE4OGU3YTkzNjcxZmMzZTliMTJlMjRlNWUwZDdkY2FmM2M0NWQwM2IzNzBmZDc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-0b9RqUrnoC1Y_Sjcdv60XQf9-4zOrhPLBkUGmO97uQ) Так и не поняла, почему при запуске контейнера возникла ошибка, решила отправить уже без него

@sirin7 если такая ошибка то нужно посмотреть на пути к бд - что и куда собирается и откуда запускается

скорее всего или проблема с доступом к файлу бд или он лежит где-то куда у приложения нет доступа

2024-09-12 08:58 UTC, dirtymew requested changes
Привет Светлана

дал рекомендации и идеи того в чем может быть проблема с докером

если не будешь доделывать - верни на ревью - готов принять работу

2024-09-12 08:58 UTC, dirtymew commented on helpers/checkTask.go
> +package helpers
@sirin7 файлы helpers/checkTask.go и  helpers/nextDate.go нужно переименовать

2024-09-12 08:58 UTC, dirtymew commented on database/delete_task.go
> +		log.Printf("failed to delete task with ID: %d", id)
логировать лучше на одном уровне  я бы на уровне хранилища это не делал 

если нужно добавить контекст то лучше обернуть ошибку

2024-09-12 08:58 UTC, dirtymew commented on database/delete_task.go
> +func DoneTask(db *sql.DB, id int) (*models.Task, error) {
лучше сделать структуру и не передавать все время подключение

посмотри как сделано было в задании про посылки

2024-09-12 10:14 UTC, sirin7 commented
> Привет Светлана
> 
> Дальние рекомендации и идеи того, в чем может быть проблема с докером
> 
> если не будешь доделывать - верни на ревью - готов принять работу

Привет, спасибо!
не успею уже доделать до дедлайна( буду потом доделывать)
Просьба принять как есть

2024-11-07 16:49 UTC, merged